services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PW}
    ports:
      - '${DB_PORT}:3306'
    expose:
      - '3306'
    volumes:
      - "${DB_DATA}:/var/lib/mysql:rw"
    user: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${MYADMIN_PORT}:80
    links:
      - "mysql:db"
